# Generated by Django 2.0.7 on 2018-07-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
                ('is_done', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
