# Generated by Django 2.0.7 on 2018-07-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_taskgroup_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='name',
            field=models.CharField(default='L', max_length=200),
            preserve_default=False,
        ),
    ]
