# Generated by Django 2.0.7 on 2018-07-31 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_auto_20180731_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroup',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todoapp.TaskGroup'),
            preserve_default=False,
        ),
    ]
