# Generated by Django 2.0.7 on 2018-08-15 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AppUserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showDone', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduyapp.AppUserSettings'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='taskGroups',
            field=models.ManyToManyField(to='scheduyapp.TaskGroup'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='tasks',
            field=models.ManyToManyField(to='scheduyapp.Task'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
