# Generated by Django 2.0.7 on 2018-08-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduyapp', '0003_auto_20180815_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='settings',
        ),
        migrations.AddField(
            model_name='appuser',
            name='showDoneTaskSettings',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AppUserSettings',
        ),
    ]
