# Generated by Django 2.0.7 on 2018-08-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduyapp', '0004_auto_20180815_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='showDoneTaskSettings',
            new_name='showDonePreference',
        ),
    ]
