# Generated by Django 2.0.7 on 2018-09-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduyapp', '0008_auto_20180918_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskgroup',
            options={'verbose_name': 'Group'},
        ),
    ]
