# Generated by Django 2.0.7 on 2018-09-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduyapp', '0009_auto_20180918_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskgroup',
            options={},
        ),
        migrations.AddField(
            model_name='appuser',
            name='taskOrderPreference',
            field=models.CharField(default='-priority', max_length=20, verbose_name='Task order'),
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduyapp.TaskGroup', verbose_name='Group'),
        ),
    ]
