# Generated by Django 2.0.7 on 2018-09-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduyapp', '0011_appuser_datetimeformatpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='orderIndex',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
