# Generated by Django 2.0.7 on 2018-09-20 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduyapp', '0012_taskgroup_orderindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Updated at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='color',
            field=models.CharField(default='whitesmoke', max_length=30, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
    ]
