# Generated by Django 2.0.7 on 2018-09-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduyapp', '0013_auto_20180920_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroup',
            name='updatedAt',
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='orderIndex',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
