# Generated by Django 2.0.7 on 2018-09-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduyapp', '0014_auto_20180921_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.CharField(blank=True, max_length=150, verbose_name='Details'),
        ),
    ]
