# Generated by Django 2.0.7 on 2019-07-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduyapp', '0015_auto_20180927_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_user_id', models.IntegerField()),
                ('details', models.CharField(blank=True, max_length=150, verbose_name='Details')),
                ('notification_time', models.DateTimeField(verbose_name='Notification time')),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduyapp.Notification', verbose_name='Notification'),
        ),
    ]
