# Generated by Django 2.0.7 on 2019-07-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduyapp', '0016_auto_20190705_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notification_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notification time'),
        ),
    ]
