# Generated by Django 2.0.7 on 2019-07-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduyapp', '0018_auto_20190705_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
        migrations.AddField(
            model_name='appuser',
            name='notifications',
            field=models.ManyToManyField(to='scheduyapp.Notification'),
        ),
    ]
