# Generated by Django 2.0.7 on 2019-07-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduyapp', '0020_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='messengerId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='messengerNotifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='pageNotifications',
            field=models.BooleanField(default=True),
        ),
    ]
