# Generated by Django 2.0.7 on 2019-07-06 19:18

from django.db import migrations, models
import scheduyapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduyapp', '0021_auto_20190706_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=60)),
                ('expirationDate', models.DateTimeField(default=scheduyapp.models.get_default_token_expirationDate)),
                ('messengerId', models.IntegerField()),
            ],
        ),
    ]
