# Generated by Django 2.0.7 on 2019-08-23 19:19

from django.db import migrations, models
import scheduyapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduyapp', '0023_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('expirationDate', models.DateTimeField(default=scheduyapp.models.get_default_email_token_expirationDate)),
                ('token', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='emailConfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='toLang',
            field=models.CharField(blank=True, default='en', max_length=2, null=True),
        ),
    ]
